# Generated by Django 4.1.5 on 2023-01-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZakazVidaUslRab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('telefon', models.CharField(max_length=150, verbose_name='Телефон')),
                ('data', models.DateField(verbose_name='Дата')),
                ('avto', models.CharField(max_length=200, verbose_name='Марка и модель авто')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
