# Generated by Django 4.1.4 on 2023-01-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uslugi', '0002_create_tcech_obsluz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagn', models.CharField(max_length=200, verbose_name='Диагностика')),
                ('vid_diagn', models.CharField(choices=[('1', 'Диагностика подвески'), ('2', 'Диагностика двигателя'), ('3', 'Диагностика турбин'), ('4', 'Диагностика электрооборудования'), ('5', 'Компьютерная диагностика')], default='1', max_length=200, verbose_name='Вид дагностики')),
                ('repair_description_diagn', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид диагностики',
                'verbose_name_plural': 'Виды диагностики',
            },
        ),
    ]
